id: P3693B1B3
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: it
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    edc5047d52454688ae927360b6a60a52:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    7da7927f10be4d6b84f2fc1d9bf84bac:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    156d5627803243d4a8f111eee309c60c:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    773fbe113283483889275f2fefb4f160:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    871ce1bb65b5470c97a21fa0b5d29ea7:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    e0dfa0e266c74dd4b89fdbbf6e427b0a:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    cd613c0aa106485d8f7f5ef77ea7d698:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    c87e41df32684e7799a9367c8d44a165:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    38c09560288e4dee9406373e935a3a92:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    443195079c5a4e0d99ae8bdf59c3e659:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    25c4a4a4b8ff4385ad59ad14983ee762:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.014110'
last_modified_at: '2022-03-01T06:06:38.014113'
